<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           eevents
    table           EveBibliograpyRef_tab
      integer         irn
      table           CatRefType_tab
        text short      CatRefType
      end
      table           CatRefValue_tab
        text short      CatRefValue
      end
      text long       CatTitle
      table           CatAuthorsRef_tab
        text short      NamFullName
        text short      NamCitedName
      end
      tuple           CatPublishedByRef
        text short      NamFullName
        text short      NamCitedName
      end
      date            CatPublicationDate
      text short      CatPublicationCity
    end
  end
?>
<!-- Data -->
<table name="eevents">

  <!-- Row 1 -->
  <tuple>
  </tuple>

  <!-- Row 2 -->
  <tuple>
  </tuple>

  <!-- Row 3 -->
  <tuple>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3038</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/16995941</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Exhibition of the paintings of the late Thomas Cole: at the Gallery of the American Arts-Union</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Snowden &amp; Prall</atom>
          <atom name="NamCitedName">Snowden &amp; Prall</atom>
        </tuple>
        <atom name="CatPublicationDate">1848</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
  </tuple>

  <!-- Row 6 -->
  <tuple>
  </tuple>

  <!-- Row 7 -->
  <tuple>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2992</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/82781504</atom>
          </tuple>
        </table>
        <atom name="CatTitle">First annual exhibition of the Yale School of the Fine Arts, founded as a department of Yale College, by the late Augustus Russell Street</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Yale University</atom>
          <atom name="NamCitedName">Yale University</atom>
        </tuple>
        <atom name="CatPublicationDate">1867</atom>
        <atom name="CatPublicationCity">New Haven</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 9 -->
  <tuple>
  </tuple>

  <!-- Row 10 -->
  <tuple>
  </tuple>

  <!-- Row 11 -->
  <tuple>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2835</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/79101587</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue, descriptive and instructive, of Catlin's Indian cartoons : portraits, types and customs, 600 paintings in oil with 20,000 full length figures ... and 27 canvas paintings of Lasalle's discoveries</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Baker and Godwin</atom>
          <atom name="NamCitedName">Baker and Godwin</atom>
        </tuple>
        <atom name="CatPublicationDate">1871</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 13 -->
  <tuple>
  </tuple>

  <!-- Row 14 -->
  <tuple>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2387</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/181807661</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the forty-ninth annual exhibition of the National Academy of Design, 1874</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">National Academy of Design</atom>
          <atom name="NamCitedName">National Academy of Design</atom>
        </tuple>
        <atom name="CatPublicationDate">1874</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 16 -->
  <tuple>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2865</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/32443061</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the ninth annual exhibition of the American Society of Painters in Water Colors: held at the galleries of the National Academy of Design</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">American Society of Painters in Water Colors</atom>
          <atom name="NamCitedName">American Society of Painters in Water Colors</atom>
        </tuple>
        <atom name="CatPublicationDate">1876</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 18 -->
  <tuple>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2866</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/6642154</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Academy sketches, comprising reproductions in fac-simile from drawings by the artists, of 110 of the pictures in the annual exhibition for 1877 of the National academy of design, with descriptive notes by "Nemo"</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">G. P. Putnam's Sons</atom>
          <atom name="NamCitedName">G. P. Putnam's Sons</atom>
        </tuple>
        <atom name="CatPublicationDate">1877</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 20 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2899</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/81508848</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Illustrated art notes upon the fifty-seventh annual exhibition</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">National Academy of Design</atom>
          <atom name="NamCitedName">National Academy of Design</atom>
        </tuple>
        <atom name="CatPublicationDate">1882</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 21 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2795</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/25712473</atom>
          </tuple>
        </table>
        <atom name="CatTitle">The private collection of Thomas B. Clarke of New York: exhibited at American Art Gallery, New York, Dec. 28, 1883 to Jan. 12, 1884</atom>
        <table name="CatAuthorsRef_tab">
          <tuple>
            <atom name="NamFullName">American Art Association</atom>
            <atom name="NamCitedName">American Art Association</atom>
          </tuple>
        </table>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Studio Press</atom>
          <atom name="NamCitedName">Studio Press</atom>
        </tuple>
        <atom name="CatPublicationDate">1883</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 22 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2901</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/859163561</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the third annual exposition of the New England Manufacturers' and Mechanics' Institute: opened September 5th, 1883, at the exhibition building, on Huntington Avenue, in the city of Boston, Mass.</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Tolman &amp; White</atom>
          <atom name="NamCitedName">Tolman &amp; White</atom>
        </tuple>
        <atom name="CatPublicationDate">1883</atom>
        <atom name="CatPublicationCity">Boston</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 23 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2816</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/122368777</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Pennsylvania Academy of the Fine Arts: 56th annual exhibition, 1885</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
          <atom name="NamCitedName">Pennsylvania Academy of the Fine Arts</atom>
        </tuple>
        <atom name="CatPublicationDate">1885</atom>
        <atom name="CatPublicationCity">Philadelphia</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 24 -->
  <tuple>
  </tuple>

  <!-- Row 25 -->
  <tuple>
  </tuple>

  <!-- Row 26 -->
  <tuple>
  </tuple>

  <!-- Row 27 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2767</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/122332080</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Pennsylvania Academy of the Fine Arts: 59th Annual Exhibition, 1889</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
          <atom name="NamCitedName">Pennsylvania Academy of the Fine Arts</atom>
        </tuple>
        <atom name="CatPublicationDate">1889</atom>
        <atom name="CatPublicationCity">Philadelphia</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 28 -->
  <tuple>
  </tuple>

  <!-- Row 29 -->
  <tuple>
  </tuple>

  <!-- Row 30 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2984</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/64070432</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of paintings exhibited by the following American artists: J. Wells Champney, William M. Chase, Charles Melville Dewey, C. Harry Eaton, F. K. M. Rehn, F. D. Millet, Robt. C. Minor, H. R. Poore, Frederic Remington, Carleton Wiggins. At the American Art Galleries, beginning April 7th</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">American Art Association</atom>
          <atom name="NamCitedName">American Art Association</atom>
        </tuple>
        <atom name="CatPublicationDate">1890</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 31 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3117</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/27292495</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the twelfth exhibition of the Society of American Artists, MDCCCXC</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Society of American Artists</atom>
          <atom name="NamCitedName">Society of American Artists</atom>
        </tuple>
        <atom name="CatPublicationDate">1890</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 32 -->
  <tuple>
  </tuple>

  <!-- Row 33 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2798</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/81817854</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the T.B. Clarke collection of American pictures. Exhibition Oct. 13 to Nov. 28, 1891.</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
          <atom name="NamCitedName">Pennsylvania Academy of the Fine Arts</atom>
        </tuple>
        <atom name="CatPublicationDate">1891</atom>
        <atom name="CatPublicationCity">Philadelphia</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 34 -->
  <tuple>
  </tuple>

  <!-- Row 35 -->
  <tuple>
  </tuple>

  <!-- Row 36 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2353</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/1250196</atom>
          </tuple>
        </table>
        <atom name="CatTitle">The Book of the fair: an historical and descriptive presentation of the world's science, art, and industry, as viewed through the Columbian Exposition at Chicago in 1893</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">The Bancroft Company</atom>
          <atom name="NamCitedName">The Bancroft Company</atom>
        </tuple>
        <atom name="CatPublicationDate">1895</atom>
        <atom name="CatPublicationCity">Chicago</atom>
      </tuple>
      <tuple>
        <atom name="InternalReferenceNumber">2361</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/79361989</atom>
          </tuple>
        </table>
        <atom name="CatTitle">World's Columbian Exposition. Official publications. Revised catalogue Department of Fine Arts with index of exhibitors</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">W. B. Conkey Co.</atom>
          <atom name="NamCitedName">W. B. Conkey Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1893</atom>
        <atom name="CatPublicationCity">Chicago</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 37 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3819</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/46827414</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the first annual exhibition</atom>
        <table name="CatAuthorsRef_tab">
          <tuple>
            <atom name="NamFullName">Cleveland Art Association</atom>
            <atom name="NamCitedName">Cleveland Art Association</atom>
          </tuple>
        </table>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Cleveland Printing &amp; Publishing Co.</atom>
          <atom name="NamCitedName">Cleveland Printing &amp; Publishing Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1895</atom>
        <atom name="CatPublicationCity">Cleveland</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 38 -->
  <tuple>
  </tuple>

  <!-- Row 39 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2308</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/35315812</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the seventeenth exhibition 1895</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Society of American Artists</atom>
          <atom name="NamCitedName">Society of American Artists</atom>
        </tuple>
        <atom name="CatPublicationDate">1895</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 40 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2975</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/7323410</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue (Illustrated) Fine Arts Department Tennessee Centennial</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Olana Gallery</atom>
          <atom name="NamCitedName">Olana Gallery</atom>
        </tuple>
        <atom name="CatPublicationDate">1897</atom>
        <atom name="CatPublicationCity">Brewster, NY</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 41 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3820</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/83535534</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Catalogue of the exhibition of fine arts: Pan American Exposition, Buffalo, 1901</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Pan-American Exposition</atom>
          <atom name="NamCitedName">Pan-American Exposition</atom>
        </tuple>
        <atom name="CatPublicationDate">1901</atom>
        <atom name="CatPublicationCity">Buffalo</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 42 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3821</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/657903076</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Exhibition of water colors: flowers from southern California, by Paul de Longpré</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">M. Knoedler &amp; Co.</atom>
          <atom name="NamCitedName">M. Knoedler &amp; Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1901</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 43 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3020</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/15581048</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Exhibition of fine arts: the South Carolina Inter-State and West Indian Exposition, Charleston, South Carolina, 1901-1902: Catalogue</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Lucas-Richardson Co.</atom>
          <atom name="NamCitedName">Lucas-Richardson Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1901</atom>
        <atom name="CatPublicationCity">Charleston</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 44 -->
  <tuple>
  </tuple>

  <!-- Row 45 -->
  <tuple>
  </tuple>

  <!-- Row 46 -->
  <tuple>
  </tuple>

  <!-- Row 47 -->
  <tuple>
  </tuple>

  <!-- Row 48 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2870</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/700826134</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Paintings by Frederic Remington</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">M. Knoedler &amp; Co.</atom>
          <atom name="NamCitedName">M. Knoedler &amp; Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1908</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 49 -->
  <tuple>
  </tuple>

  <!-- Row 50 -->
  <tuple>
  </tuple>

  <!-- Row 51 -->
  <tuple>
  </tuple>

  <!-- Row 52 -->
  <tuple>
  </tuple>

  <!-- Row 53 -->
  <tuple>
  </tuple>

  <!-- Row 54 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2852</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/84014474</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Some works by James D. Smillie, N.A. 1833-1909; drawings, water colors, oil paintings, etchings</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Century Association</atom>
          <atom name="NamCitedName">Century Association</atom>
        </tuple>
        <atom name="CatPublicationDate">1910</atom>
        <atom name="CatPublicationCity">New York</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 55 -->
  <tuple>
  </tuple>

  <!-- Row 56 -->
  <tuple>
  </tuple>

  <!-- Row 57 -->
  <tuple>
  </tuple>

  <!-- Row 58 -->
  <tuple>
  </tuple>

  <!-- Row 59 -->
  <tuple>
  </tuple>

  <!-- Row 60 -->
  <tuple>
  </tuple>

  <!-- Row 61 -->
  <tuple>
  </tuple>

  <!-- Row 62 -->
  <tuple>
  </tuple>

  <!-- Row 63 -->
  <tuple>
  </tuple>

  <!-- Row 64 -->
  <tuple>
  </tuple>

  <!-- Row 65 -->
  <tuple>
  </tuple>

  <!-- Row 66 -->
  <tuple>
  </tuple>

  <!-- Row 67 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">3254</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/80548623</atom>
          </tuple>
        </table>
        <atom name="CatTitle">Fifth exhibition oil paintings by contemporary American artists</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Corcoran Gallery of Art</atom>
          <atom name="NamCitedName">Corcoran Gallery of Art</atom>
        </tuple>
        <atom name="CatPublicationDate">1914</atom>
        <atom name="CatPublicationCity">Washington, D.C.</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 68 -->
  <tuple>
  </tuple>

  <!-- Row 69 -->
  <tuple>
  </tuple>

  <!-- Row 70 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2821</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/564479</atom>
          </tuple>
        </table>
        <atom name="CatTitle">The sculpture and mural decorations of the exposition; a pictorial survey of the art of the Panama-Pacific International Exposition</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">P. Elder and Co.</atom>
          <atom name="NamCitedName">P. Elder and Co.</atom>
        </tuple>
        <atom name="CatPublicationDate">1915</atom>
        <atom name="CatPublicationCity">San Francisco</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 71 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalReferenceNumber">2763</atom>
        <table name="CatRefType_tab">
          <tuple>
            <atom name="CatRefType">Worldcat</atom>
          </tuple>
        </table>
        <table name="CatRefValue_tab">
          <tuple>
            <atom name="CatRefValue">http://www.worldcat.org/oclc/62463353</atom>
          </tuple>
        </table>
        <atom name="CatTitle">"The West thas has passed": paintings and bronzes by Charles M. Russell, the cowboy artist</atom>
        <tuple name="CatPublishedByRef">
          <atom name="NamFullName">Thurber's Galleries</atom>
          <atom name="NamCitedName">Thurber's Galleries</atom>
        </tuple>
        <atom name="CatPublicationDate">1916</atom>
        <atom name="CatPublicationCity">Chicago</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 72 -->
  <tuple>
  </tuple>

  <!-- Row 73 -->
  <tuple>
  </tuple>

  <!-- Row 74 -->
  <tuple>
    <table name="EveBibliograpyRef_tab">
      <tuple>