<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           eevents
    text long       EveEventTitle
    date            DatCommencementDate
    date            DatCompletionDate
    table           EveEventOrganisersRef_tab
      text short      NamFullName
    end
    table           VenVenueNameRef_tab
      text short      NamFullName
    end
    table           ObjAttachedObjectsRef_tab
      integer         irn
    end
  end
?>
<!-- Data -->
<table name="eevents">

  <!-- Row 1 -->
  <tuple>
    <atom name="EveEventTitle">25 Years of Texas Monthly Photographs</atom>
    <atom name="DatCommencementDate">1998-01-30</atom>
    <atom name="DatCompletionDate">1998-03-01</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Lyndon Baines Johnson Library</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Lyndon Baines Johnson Library</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">16172</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="EveEventTitle">100 Great American Photographs</atom>
    <atom name="DatCommencementDate">2006-07-01</atom>
    <atom name="DatCompletionDate">2006-08-20</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">54966</atom>
      </tuple>
      <tuple>
        <atom name="irn">114426</atom>
      </tuple>
      <tuple>
        <atom name="irn">16343</atom>
      </tuple>
      <tuple>
        <atom name="irn">50959</atom>
      </tuple>
      <tuple>
        <atom name="irn">102296</atom>
      </tuple>
      <tuple>
        <atom name="irn">92113</atom>
      </tuple>
      <tuple>
        <atom name="irn">109020</atom>
      </tuple>
      <tuple>
        <atom name="irn">74009</atom>
      </tuple>
      <tuple>
        <atom name="irn">23644</atom>
      </tuple>
      <tuple>
        <atom name="irn">77368</atom>
      </tuple>
      <tuple>
        <atom name="irn">50385</atom>
      </tuple>
      <tuple>
        <atom name="irn">80707</atom>
      </tuple>
      <tuple>
        <atom name="irn">4635</atom>
      </tuple>
      <tuple>
        <atom name="irn">55797</atom>
      </tuple>
      <tuple>
        <atom name="irn">136953</atom>
      </tuple>
      <tuple>
        <atom name="irn">140638</atom>
      </tuple>
      <tuple>
        <atom name="irn">45010</atom>
      </tuple>
      <tuple>
        <atom name="irn">111172</atom>
      </tuple>
      <tuple>
        <atom name="irn">68094</atom>
      </tuple>
      <tuple>
        <atom name="irn">1249</atom>
      </tuple>
      <tuple>
        <atom name="irn">127176</atom>
      </tuple>
      <tuple>
        <atom name="irn">14334</atom>
      </tuple>
      <tuple>
        <atom name="irn">83904</atom>
      </tuple>
      <tuple>
        <atom name="irn">100759</atom>
      </tuple>
      <tuple>
        <atom name="irn">15437</atom>
      </tuple>
      <tuple>
        <atom name="irn">136210</atom>
      </tuple>
      <tuple>
        <atom name="irn">107182</atom>
      </tuple>
      <tuple>
        <atom name="irn">29601</atom>
      </tuple>
      <tuple>
        <atom name="irn">122276</atom>
      </tuple>
      <tuple>
        <atom name="irn">32071</atom>
      </tuple>
      <tuple>
        <atom name="irn">150745</atom>
      </tuple>
      <tuple>
        <atom name="irn">84576</atom>
      </tuple>
      <tuple>
        <atom name="irn">62351</atom>
      </tuple>
      <tuple>
        <atom name="irn">75353</atom>
      </tuple>
      <tuple>
        <atom name="irn">9118</atom>
      </tuple>
      <tuple>
        <atom name="irn">37533</atom>
      </tuple>
      <tuple>
        <atom name="irn">72576</atom>
      </tuple>
      <tuple>
        <atom name="irn">162300</atom>
      </tuple>
      <tuple>
        <atom name="irn">32365</atom>
      </tuple>
      <tuple>
        <atom name="irn">67465</atom>
      </tuple>
      <tuple>
        <atom name="irn">64777</atom>
      </tuple>
      <tuple>
        <atom name="irn">94233</atom>
      </tuple>
      <tuple>
        <atom name="irn">97563</atom>
      </tuple>
      <tuple>
        <atom name="irn">40558</atom>
      </tuple>
      <tuple>
        <atom name="irn">133477</atom>
      </tuple>
      <tuple>
        <atom name="irn">74923</atom>
      </tuple>
      <tuple>
        <atom name="irn">9844</atom>
      </tuple>
      <tuple>
        <atom name="irn">134797</atom>
      </tuple>
      <tuple>
        <atom name="irn">82132</atom>
      </tuple>
      <tuple>
        <atom name="irn">27430</atom>
      </tuple>
      <tuple>
        <atom name="irn">35024</atom>
      </tuple>
      <tuple>
        <atom name="irn">14681</atom>
      </tuple>
      <tuple>
        <atom name="irn">32196</atom>
      </tuple>
      <tuple>
        <atom name="irn">7073</atom>
      </tuple>
      <tuple>
        <atom name="irn">101614</atom>
      </tuple>
      <tuple>
        <atom name="irn">22541</atom>
      </tuple>
      <tuple>
        <atom name="irn">150300</atom>
      </tuple>
      <tuple>
        <atom name="irn">53079</atom>
      </tuple>
      <tuple>
        <atom name="irn">78686</atom>
      </tuple>
      <tuple>
        <atom name="irn">67337</atom>
      </tuple>
      <tuple>
        <atom name="irn">73785</atom>
      </tuple>
      <tuple>
        <atom name="irn">60910</atom>
      </tuple>
      <tuple>
        <atom name="irn">139973</atom>
      </tuple>
      <tuple>
        <atom name="irn">153976</atom>
      </tuple>
      <tuple>
        <atom name="irn">113314</atom>
      </tuple>
      <tuple>
        <atom name="irn">46984</atom>
      </tuple>
      <tuple>
        <atom name="irn">34570</atom>
      </tuple>
      <tuple>
        <atom name="irn">159291</atom>
      </tuple>
      <tuple>
        <atom name="irn">162213</atom>
      </tuple>
      <tuple>
        <atom name="irn">71277</atom>
      </tuple>
      <tuple>
        <atom name="irn">94537</atom>
      </tuple>
      <tuple>
        <atom name="irn">89744</atom>
      </tuple>
      <tuple>
        <atom name="irn">34927</atom>
      </tuple>
      <tuple>
        <atom name="irn">67232</atom>
      </tuple>
      <tuple>
        <atom name="irn">95533</atom>
      </tuple>
      <tuple>
        <atom name="irn">51290</atom>
      </tuple>
      <tuple>
        <atom name="irn">89504</atom>
      </tuple>
      <tuple>
        <atom name="irn">95140</atom>
      </tuple>
      <tuple>
        <atom name="irn">107016</atom>
      </tuple>
      <tuple>
        <atom name="irn">138766</atom>
      </tuple>
      <tuple>
        <atom name="irn">151366</atom>
      </tuple>
      <tuple>
        <atom name="irn">100510</atom>
      </tuple>
      <tuple>
        <atom name="irn">25045</atom>
      </tuple>
      <tuple>
        <atom name="irn">131516</atom>
      </tuple>
      <tuple>
        <atom name="irn">107274</atom>
      </tuple>
      <tuple>
        <atom name="irn">19529</atom>
      </tuple>
      <tuple>
        <atom name="irn">30186</atom>
      </tuple>
      <tuple>
        <atom name="irn">129276</atom>
      </tuple>
      <tuple>
        <atom name="irn">25975</atom>
      </tuple>
      <tuple>
        <atom name="irn">45643</atom>
      </tuple>
      <tuple>
        <atom name="irn">125566</atom>
      </tuple>
      <tuple>
        <atom name="irn">119864</atom>
      </tuple>
      <tuple>
        <atom name="irn">97612</atom>
      </tuple>
      <tuple>
        <atom name="irn">78695</atom>
      </tuple>
      <tuple>
        <atom name="irn">62350</atom>
      </tuple>
      <tuple>
        <atom name="irn">38014</atom>
      </tuple>
      <tuple>
        <atom name="irn">141413</atom>
      </tuple>
      <tuple>
        <atom name="irn">157919</atom>
      </tuple>
      <tuple>
        <atom name="irn">142927</atom>
      </tuple>
      <tuple>
        <atom name="irn">161655</atom>
      </tuple>
      <tuple>
        <atom name="irn">161656</atom>
      </tuple>
      <tuple>
        <atom name="irn">161653</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="EveEventTitle">100 Years of Artist Activity in Wyoming, 1837-1937</atom>
    <atom name="DatCommencementDate">1976-10-03</atom>
    <atom name="DatCompletionDate">1976-11-07</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">University of Wyoming, Laramie</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">University of Wyoming, Laramie</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">108959</atom>
      </tuple>
      <tuple>
        <atom name="irn">13142</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="EveEventTitle">100 Years of Autochrome</atom>
    <atom name="DatCommencementDate">2007-08-18</atom>
    <atom name="DatCompletionDate">2008-07-27</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
      <tuple>
        <atom name="NamFullName">Sylvie Penichon</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">64998</atom>
      </tuple>
      <tuple>
        <atom name="irn">6316</atom>
      </tuple>
      <tuple>
        <atom name="irn">54284</atom>
      </tuple>
      <tuple>
        <atom name="irn">63616</atom>
      </tuple>
      <tuple>
        <atom name="irn">53232</atom>
      </tuple>
      <tuple>
        <atom name="irn">29594</atom>
      </tuple>
      <tuple>
        <atom name="irn">14951</atom>
      </tuple>
      <tuple>
        <atom name="irn">7016</atom>
      </tuple>
      <tuple>
        <atom name="irn">135980</atom>
      </tuple>
      <tuple>
        <atom name="irn">38013</atom>
      </tuple>
      <tuple>
        <atom name="irn">32924</atom>
      </tuple>
      <tuple>
        <atom name="irn">109646</atom>
      </tuple>
      <tuple>
        <atom name="irn">24189</atom>
      </tuple>
      <tuple>
        <atom name="irn">134541</atom>
      </tuple>
      <tuple>
        <atom name="irn">102346</atom>
      </tuple>
      <tuple>
        <atom name="irn">109816</atom>
      </tuple>
      <tuple>
        <atom name="irn">54628</atom>
      </tuple>
      <tuple>
        <atom name="irn">124117</atom>
      </tuple>
      <tuple>
        <atom name="irn">23841</atom>
      </tuple>
      <tuple>
        <atom name="irn">45270</atom>
      </tuple>
      <tuple>
        <atom name="irn">7995</atom>
      </tuple>
      <tuple>
        <atom name="irn">80421</atom>
      </tuple>
      <tuple>
        <atom name="irn">100434</atom>
      </tuple>
      <tuple>
        <atom name="irn">29155</atom>
      </tuple>
      <tuple>
        <atom name="irn">48664</atom>
      </tuple>
      <tuple>
        <atom name="irn">25288</atom>
      </tuple>
      <tuple>
        <atom name="irn">23942</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="EveEventTitle">200 Years of American Illustration</atom>
    <atom name="DatCommencementDate">1976-09-10</atom>
    <atom name="DatCompletionDate">1977-04-15</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">New-York Historical Society</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">New-York Historical Society</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">107393</atom>
      </tuple>
      <tuple>
        <atom name="irn">54553</atom>
      </tuple>
      <tuple>
        <atom name="irn">109193</atom>
      </tuple>
      <tuple>
        <atom name="irn">40308</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="EveEventTitle">1846: Portrait of the Nation</atom>
    <atom name="DatCommencementDate">1996-04-12</atom>
    <atom name="DatCompletionDate">1996-08-18</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Portrait Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Portrait Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">43972</atom>
      </tuple>
      <tuple>
        <atom name="irn">116320</atom>
      </tuple>
      <tuple>
        <atom name="irn">49495</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="EveEventTitle">1920 Amerikafotografie 1940</atom>
    <atom name="DatCommencementDate">1979-08-23</atom>
    <atom name="DatCompletionDate">1979-10-28</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Kunsthaus Zürich</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Kunsthaus Zürich</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">116125</atom>
      </tuple>
      <tuple>
        <atom name="irn">131633</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="EveEventTitle">1940 Annual Exhibition of Contemporary American Art</atom>
    <atom name="DatCommencementDate">1940-01-10</atom>
    <atom name="DatCompletionDate">1940-02-18</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Associated American Artists</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Whitney Museum of American Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">27014</atom>
      </tuple>
      <tuple>
        <atom name="irn">97617</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="EveEventTitle">100th Anniversary of the Calgary Stampede</atom>
    <atom name="DatCommencementDate">2012-06-01</atom>
    <atom name="DatCompletionDate">2012-07-31</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Glenbow Museum</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Glenbow Museum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">15931</atom>
      </tuple>
      <tuple>
        <atom name="irn">66418</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="EveEventTitle">113th Annual Exhibition</atom>
    <atom name="DatCommencementDate">1918-02-03</atom>
    <atom name="DatCompletionDate">1918-03-24</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">34913</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <atom name="EveEventTitle">128th Annual Exhibition of the Pennsylvania Academy of the Fine Arts</atom>
    <atom name="DatCommencementDate">1933-01-29</atom>
    <atom name="DatCompletionDate">1933-03-19</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">5350</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <atom name="EveEventTitle">150th Anniversary Exhibition</atom>
    <atom name="DatCommencementDate">1955-01-15</atom>
    <atom name="DatCompletionDate">1955-05-13</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
      <tuple>
        <atom name="NamFullName">Sala de la Direccion General de Bellas Artes, Biblioteca National (Spain)</atom>
      </tuple>
      <tuple>
        <atom name="NamFullName">Palazzo Strozzi</atom>
      </tuple>
      <tuple>
        <atom name="NamFullName">Tiroler Landesmuseum Ferdinandeum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">17019</atom>
      </tuple>
      <tuple>
        <atom name="irn">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="EveEventTitle">15th Annual Exhibition</atom>
    <atom name="DatCommencementDate">1887-09-07</atom>
    <atom name="DatCompletionDate">1887-10-22</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Interstate Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Interstate Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <atom name="EveEventTitle">1930's</atom>
    <atom name="DatCommencementDate">1984-02-07</atom>
    <atom name="DatCompletionDate">1984-03-14</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">University of North Texas</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">University of North Texas</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">5541</atom>
      </tuple>
      <tuple>
        <atom name="irn">138788</atom>
      </tuple>
      <tuple>
        <atom name="irn">43720</atom>
      </tuple>
      <tuple>
        <atom name="irn">46884</atom>
      </tuple>
      <tuple>
        <atom name="irn">130860</atom>
      </tuple>
      <tuple>
        <atom name="irn">50981</atom>
      </tuple>
      <tuple>
        <atom name="irn">146483</atom>
      </tuple>
      <tuple>
        <atom name="irn">6550</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <atom name="EveEventTitle">19th Century America, Paintings and Sculpture: An Exhibition in Celebration of the Hundredth Anniversary of the Metropolitan Museum of Art</atom>
    <atom name="DatCommencementDate">1970-04-16</atom>
    <atom name="DatCompletionDate">1970-09-07</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Metropolitan Museum of Art</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Metropolitan Museum of Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">68100</atom>
      </tuple>
      <tuple>
        <atom name="irn">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <atom name="EveEventTitle">19th Century American Paintings Symposium</atom>
    <atom name="DatCommencementDate">1979-03-03</atom>
    <atom name="DatCompletionDate">1979-03-26</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Amon Carter Museum of American Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <atom name="EveEventTitle">19th Century American Topographic Painters</atom>
    <atom name="DatCommencementDate">1974-11-21</atom>
    <atom name="DatCompletionDate">1975-01-05</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Lowe Art Museum</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Lowe Art Museum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">132283</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <atom name="EveEventTitle">19th Century View of America</atom>
    <atom name="DatCommencementDate">1979-09-27</atom>
    <atom name="DatCompletionDate">1979-11-19</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Roswell Museum and Art Center</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Roswell Museum and Art Center</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">118900</atom>
      </tuple>
      <tuple>
        <atom name="irn">114151</atom>
      </tuple>
      <tuple>
        <atom name="irn">1596</atom>
      </tuple>
      <tuple>
        <atom name="irn">142680</atom>
      </tuple>
      <tuple>
        <atom name="irn">20936</atom>
      </tuple>
      <tuple>
        <atom name="irn">86602</atom>
      </tuple>
      <tuple>
        <atom name="irn">133545</atom>
      </tuple>
      <tuple>
        <atom name="irn">52466</atom>
      </tuple>
      <tuple>
        <atom name="irn">180</atom>
      </tuple>
      <tuple>
        <atom name="irn">15322</atom>
      </tuple>
      <tuple>
        <atom name="irn">92440</atom>
      </tuple>
      <tuple>
        <atom name="irn">117652</atom>
      </tuple>
      <tuple>
        <atom name="irn">114129</atom>
      </tuple>
      <tuple>
        <atom name="irn">59036</atom>
      </tuple>
      <tuple>
        <atom name="irn">47012</atom>
      </tuple>
      <tuple>
        <atom name="irn">38498</atom>
      </tuple>
      <tuple>
        <atom name="irn">92362</atom>
      </tuple>
      <tuple>
        <atom name="irn">103851</atom>
      </tuple>
      <tuple>
        <atom name="irn">84160</atom>
      </tuple>
      <tuple>
        <atom name="irn">103852</atom>
      </tuple>
      <tuple>
        <atom name="irn">85876</atom>
      </tuple>
      <tuple>
        <atom name="irn">96890</atom>
      </tuple>
      <tuple>
        <atom name="irn">39996</atom>
      </tuple>
      <tuple>
        <atom name="irn">141969</atom>
      </tuple>
      <tuple>
        <atom name="irn">20393</atom>
      </tuple>
      <tuple>
        <atom name="irn">93335</atom>
      </tuple>
      <tuple>
        <atom name="irn">104497</atom>
      </tuple>
      <tuple>
        <atom name="irn">132710</atom>
      </tuple>
      <tuple>
        <atom name="irn">64722</atom>
      </tuple>
      <tuple>
        <atom name="irn">75398</atom>
      </tuple>
      <tuple>
        <atom name="irn">72205</atom>
      </tuple>
      <tuple>
        <atom name="irn">52838</atom>
      </tuple>
      <tuple>
        <atom name="irn">140934</atom>
      </tuple>
      <tuple>
        <atom name="irn">124542</atom>
      </tuple>
      <tuple>
        <atom name="irn">36005</atom>
      </tuple>
      <tuple>
        <atom name="irn">97433</atom>
      </tuple>
      <tuple>
        <atom name="irn">29122</atom>
      </tuple>
      <tuple>
        <atom name="irn">84334</atom>
      </tuple>
      <tuple>
        <atom name="irn">98645</atom>
      </tuple>
      <tuple>
        <atom name="irn">68149</atom>
      </tuple>
      <tuple>
        <atom name="irn">46313</atom>
      </tuple>
      <tuple>
        <atom name="irn">54241</atom>
      </tuple>
      <tuple>
        <atom name="irn">118225</atom>
      </tuple>
      <tuple>
        <atom name="irn">146608</atom>
      </tuple>
      <tuple>
        <atom name="irn">53508</atom>
      </tuple>
      <tuple>
        <atom name="irn">138559</atom>
      </tuple>
      <tuple>
        <atom name="irn">125359</atom>
      </tuple>
      <tuple>
        <atom name="irn">99029</atom>
      </tuple>
      <tuple>
        <atom name="irn">23673</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <atom name="EveEventTitle">20th Century American Art from the Collection of the Fort Worth Art Museum</atom>
    <atom name="DatCommencementDate">1978-01-28</atom>
    <atom name="DatCompletionDate">1978-02-26</atom>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Beaumont Art Museum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">148911</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 20 -->
  <tuple>
    <atom name="EveEventTitle">20th Century Paintings</atom>
    <atom name="DatCommencementDate">1966-09-01</atom>
    <atom name="DatCompletionDate">1966-09-13</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Fort Worth Art Center</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Fort Worth Art Center</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">63537</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 21 -->
  <tuple>
    <atom name="EveEventTitle">20th Century Women in Texas Art</atom>
    <atom name="DatCommencementDate">1974-09-01</atom>
    <atom name="DatCompletionDate">1974-11-11</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Laguna Gloria Art Museum</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Laguna Gloria Art Museum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">84254</atom>
      </tuple>
      <tuple>
        <atom name="irn">64561</atom>
      </tuple>
      <tuple>
        <atom name="irn">122414</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 22 -->
  <tuple>
    <atom name="EveEventTitle">25th Anniversary Year Exhibition of Marsden Hartley and John Marin</atom>
    <atom name="DatCommencementDate">1966-02-12</atom>
    <atom name="DatCompletionDate">1966-03-27</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">La Jolla Museum of Art</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">La Jolla Museum of Art</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">46502</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 23 -->
  <tuple>
    <atom name="EveEventTitle">32nd Annual Show</atom>
    <atom name="DatCommencementDate">1957-12-31</atom>
    <atom name="DatCompletionDate">1958-01-25</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Downtown Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Downtown Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">127046</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 24 -->
  <tuple>
    <atom name="EveEventTitle">41st Anniversary Exhibition</atom>
    <atom name="DatCommencementDate">1966-10-18</atom>
    <atom name="DatCompletionDate">1966-11-12</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Downtown Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Downtown Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="irn">89137</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 25 -->
  <tuple>