<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3374</atom>
        <atom name="NamFullName">John Abbot</atom>
        <atom name="SummaryData">Abbot, John</atom>
        <atom name="BioLabel">John Abbot (1751-ca. 1840)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">British</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 1, 1751</atom>
        <atom name="BioBirthPlace">London, England</atom>
        <atom name="BioBirthEarliestDate">1751-06-01</atom>
        <atom name="BioBirthLatestDate">1751-06-01</atom>
        <atom name="BioDeathDate">ca. 1840</atom>
        <atom name="BioDeathPlace">Bulloch County, Georgia</atom>
        <atom name="BioDeathEarliestDate">1840</atom>
        <atom name="BioDeathLatestDate">1841</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1618</atom>
        <atom name="NamFullName">James William Abert</atom>
        <atom name="SummaryData">Abert, James William</atom>
        <atom name="BioLabel">James William Abert (1820-1871)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Nov. 18, 1820</atom>
        <atom name="BioBirthPlace">Mount Holly, New Jersey</atom>
        <atom name="BioBirthEarliestDate">1820-11-18</atom>
        <atom name="BioBirthLatestDate">1820-11-18</atom>
        <atom name="BioDeathDate">1871</atom>
        <atom name="BioDeathPlace">Newport, Kentucky</atom>
        <atom name="BioDeathEarliestDate">1871</atom>
        <atom name="BioDeathLatestDate">1871</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1838</atom>
        <atom name="NamFullName">Louis B. Akin</atom>
        <atom name="SummaryData">Akin, Louis B.</atom>
        <atom name="BioLabel">Louis B. Akin (1868-1913)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 6, 1868</atom>
        <atom name="BioBirthPlace">Corvallis, Oregeon</atom>
        <atom name="BioBirthEarliestDate">1868-06-06</atom>
        <atom name="BioBirthLatestDate">1868-06-06</atom>
        <atom name="BioDeathDate">Jan. 5, 1913</atom>
        <atom name="BioDeathPlace">Flagstaff, Arizona</atom>
        <atom name="BioDeathEarliestDate">1913-01-05</atom>
        <atom name="BioDeathLatestDate">1913-01-05</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 20 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 21 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 22 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 23 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 24 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 25 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2856</atom>
        <atom name="NamFullName">Robert Gardner</atom>
        <atom name="SummaryData">Gardner, Robert</atom>
        <atom name="BioLabel">Robert Gardner (b. 1919)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1919</atom>
        <atom name="BioBirthPlace">Indianapolis, Indiana</atom>
        <atom name="BioBirthEarliestDate">1919</atom>
        <atom name="BioBirthLatestDate">1919</atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 26 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3804</atom>
        <atom name="NamFullName">Anni Albers</atom>
        <atom name="SummaryData">Albers, Anni</atom>
        <atom name="BioLabel">Anni Albers (1899-1994)</atom>
        <atom name="NamSex">Female</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">June 12, 1899</atom>
        <atom name="BioBirthPlace">Berlin, Germany</atom>
        <atom name="BioBirthEarliestDate">1899-06-12</atom>
        <atom name="BioBirthLatestDate">1899-06-12</atom>
        <atom name="BioDeathDate">May 9, 1994</atom>
        <atom name="BioDeathPlace">Orange, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1994-05-09</atom>
        <atom name="BioDeathLatestDate">1994-05-09</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2856</atom>
        <atom name="NamFullName">Robert Gardner</atom>
        <atom name="SummaryData">Gardner, Robert</atom>
        <atom name="BioLabel">Robert Gardner (b. 1919)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1919</atom>
        <atom name="BioBirthPlace">Indianapolis, Indiana</atom>
        <atom name="BioBirthEarliestDate">1919</atom>
        <atom name="BioBirthLatestDate">1919</atom>
        <atom name="BioDeathDate"></atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate"></atom>
        <atom name="BioDeathLatestDate"></atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 27 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">1692</atom>
        <atom name="NamFullName">Bohuslav Horak</atom>
        <atom name="SummaryData">Horak, Bohuslav</atom>
        <atom name="BioLabel">Bohuslav Horak (1914-2004)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">French</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Jan. 23, 1914</atom>
        <atom name="BioBirthPlace">Prague, Czechoslovakia</atom>
        <atom name="BioBirthEarliestDate">1914-01-23</atom>
        <atom name="BioBirthLatestDate">1914-01-23</atom>
        <atom name="BioDeathDate">Jan. 3, 2004</atom>
        <atom name="BioDeathPlace">Paris, France</atom>
        <atom name="BioDeathEarliestDate">2004-01-03</atom>
        <atom name="BioDeathLatestDate">2004-01-03</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 28 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3042</atom>
        <atom name="NamFullName">Josef Albers</atom>
        <atom name="SummaryData">Albers, Josef</atom>
        <atom name="BioLabel">Josef Albers (1888-1976)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Mar. 19, 1888</atom>
        <atom name="BioBirthPlace">Bottrop, Ruhr, Germany</atom>
        <atom name="BioBirthEarliestDate">1888-03-19</atom>
        <atom name="BioBirthLatestDate">1888-03-19</atom>
        <atom name="BioDeathDate">Mar. 25, 1976</atom>
        <atom name="BioDeathPlace">New Haven, Connecticut</atom>
        <atom name="BioDeathEarliestDate">1976-03-25</atom>
        <atom name="BioDeathLatestDate">1976-03-25</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">1629</atom>
        <atom name="NamFullName">Kenneth Tyler</atom>