<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table (tuple)*>
  <!ATTLIST table
            name  CDATA #REQUIRED
  >

  <!ELEMENT tuple (table|tuple|atom)*>
  <!ATTLIST tuple
            name  CDATA #IMPLIED
  >

  <!ELEMENT atom  (#PCDATA)*>
  <!ATTLIST atom
            name  CDATA #REQUIRED
            type  CDATA "text"
            size  CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 2000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
        <atom name="NamFullName">Arthur Bowen Davies</atom>
        <atom name="SummaryData">Davies, Arthur Bowen</atom>
        <atom name="BioLabel">Arthur Bowen Davies (1862-1928)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Sep. 26, 1862</atom>
        <atom name="BioBirthPlace">Utica, New York</atom>
        <atom name="BioBirthEarliestDate">1862-09-26</atom>
        <atom name="BioBirthLatestDate">1862-09-26</atom>
        <atom name="BioDeathDate">Oct. 24, 1928</atom>
        <atom name="BioDeathPlace">Florence, Italy</atom>
        <atom name="BioDeathEarliestDate">1928-10-24</atom>
        <atom name="BioDeathLatestDate">1928-10-24</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
        <atom name="NamFullName">George C. Miller</atom>
        <atom name="SummaryData">Miller, George C.</atom>
        <atom name="BioLabel">George C. Miller (1894-1965)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1894</atom>
        <atom name="BioBirthPlace">New York, New York</atom>
        <atom name="BioBirthEarliestDate">1894</atom>
        <atom name="BioBirthLatestDate">1894</atom>
        <atom name="BioDeathDate">1965</atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate">1965</atom>
        <atom name="BioDeathLatestDate">1965</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
        <atom name="NamFullName">Arthur Bowen Davies</atom>
        <atom name="SummaryData">Davies, Arthur Bowen</atom>
        <atom name="BioLabel">Arthur Bowen Davies (1862-1928)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Sep. 26, 1862</atom>
        <atom name="BioBirthPlace">Utica, New York</atom>
        <atom name="BioBirthEarliestDate">1862-09-26</atom>
        <atom name="BioBirthLatestDate">1862-09-26</atom>
        <atom name="BioDeathDate">Oct. 24, 1928</atom>
        <atom name="BioDeathPlace">Florence, Italy</atom>
        <atom name="BioDeathEarliestDate">1928-10-24</atom>
        <atom name="BioDeathLatestDate">1928-10-24</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
        <atom name="NamFullName">George C. Miller</atom>
        <atom name="SummaryData">Miller, George C.</atom>
        <atom name="BioLabel">George C. Miller (1894-1965)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1894</atom>
        <atom name="BioBirthPlace">New York, New York</atom>
        <atom name="BioBirthEarliestDate">1894</atom>
        <atom name="BioBirthLatestDate">1894</atom>
        <atom name="BioDeathDate">1965</atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate">1965</atom>
        <atom name="BioDeathLatestDate">1965</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
        <atom name="NamFullName">Arthur Bowen Davies</atom>
        <atom name="SummaryData">Davies, Arthur Bowen</atom>
        <atom name="BioLabel">Arthur Bowen Davies (1862-1928)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Sep. 26, 1862</atom>
        <atom name="BioBirthPlace">Utica, New York</atom>
        <atom name="BioBirthEarliestDate">1862-09-26</atom>
        <atom name="BioBirthLatestDate">1862-09-26</atom>
        <atom name="BioDeathDate">Oct. 24, 1928</atom>
        <atom name="BioDeathPlace">Florence, Italy</atom>
        <atom name="BioDeathEarliestDate">1928-10-24</atom>
        <atom name="BioDeathLatestDate">1928-10-24</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
        <atom name="NamFullName">George C. Miller</atom>
        <atom name="SummaryData">Miller, George C.</atom>
        <atom name="BioLabel">George C. Miller (1894-1965)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1894</atom>
        <atom name="BioBirthPlace">New York, New York</atom>
        <atom name="BioBirthEarliestDate">1894</atom>
        <atom name="BioBirthLatestDate">1894</atom>
        <atom name="BioDeathDate">1965</atom>
        <atom name="BioDeathPlace"></atom>
        <atom name="BioDeathEarliestDate">1965</atom>
        <atom name="BioDeathLatestDate">1965</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
        <atom name="NamFullName">Arthur Bowen Davies</atom>
        <atom name="SummaryData">Davies, Arthur Bowen</atom>
        <atom name="BioLabel">Arthur Bowen Davies (1862-1928)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Sep. 26, 1862</atom>
        <atom name="BioBirthPlace">Utica, New York</atom>
        <atom name="BioBirthEarliestDate">1862-09-26</atom>
        <atom name="BioBirthLatestDate">1862-09-26</atom>
        <atom name="BioDeathDate">Oct. 24, 1928</atom>
        <atom name="BioDeathPlace">Florence, Italy</atom>
        <atom name="BioDeathEarliestDate">1928-10-24</atom>
        <atom name="BioDeathLatestDate">1928-10-24</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2892</atom>
        <atom name="NamFullName">Frank Arthur Nankivell</atom>
        <atom name="SummaryData">Nankivell, Frank Arthur</atom>
        <atom name="BioLabel">Frank Arthur Nankivell (1869-1959)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">Australian</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">1869</atom>
        <atom name="BioBirthPlace">Maldon, Australia</atom>
        <atom name="BioBirthEarliestDate">1869</atom>
        <atom name="BioBirthLatestDate">1869</atom>
        <atom name="BioDeathDate">1959</atom>
        <atom name="BioDeathPlace">Florham Park, New Jersey</atom>
        <atom name="BioDeathEarliestDate">1959</atom>
        <atom name="BioDeathLatestDate">1959</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2017 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2018 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2019 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2020 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2021 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2022 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2023 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2024 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2025 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>
        <atom name="BioDeathLatestDate">1964-06-24</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2026 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
        <atom name="NamFullName">Stuart Davis</atom>
        <atom name="SummaryData">Davis, Stuart</atom>
        <atom name="BioLabel">Stuart Davis (1892-1964)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec. 7, 1892</atom>
        <atom name="BioBirthPlace">Philadelphia, Pennsylvania</atom>
        <atom name="BioBirthEarliestDate">1892-12-07</atom>
        <atom name="BioBirthLatestDate">1892-12-07</atom>
        <atom name="BioDeathDate">June 24, 1964</atom>
        <atom name="BioDeathPlace">New York, New York</atom>
        <atom name="BioDeathEarliestDate">1964-06-24</atom>