<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           CreCreatorRef_tab
      integer         irn
      text short      NamFullName
      text short      SummaryData
      text long       BioLabel
      text short      NamSex
      text short      BioNationality
      text short      BioEthnicity
      text short      BioBirthDate
      text short      BioBirthPlace
      date            BioBirthEarliestDate
      date            BioBirthLatestDate
      text short      BioDeathDate
      text short      BioDeathPlace
      date            BioDeathEarliestDate
      date            BioDeathLatestDate
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">



  <!-- Row 4000 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4001 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4002 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4003 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4004 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4005 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4006 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4007 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4008 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4009 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4010 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4011 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4012 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4013 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4014 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4015 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4016 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4017 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4018 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4019 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4020 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4021 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4022 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4023 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4024 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4025 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4026 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4027 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4028 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4029 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>
        <atom name="BioBirthPlace">Winnetka, Illinois</atom>
        <atom name="BioBirthEarliestDate">1901-12-06</atom>
        <atom name="BioBirthLatestDate">1901-12-06</atom>
        <atom name="BioDeathDate">Nov.  2, 1990</atom>
        <atom name="BioDeathPlace">Santa Fe, New Mexico</atom>
        <atom name="BioDeathEarliestDate">1990-11-02</atom>
        <atom name="BioDeathLatestDate">1990-11-02</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4030 -->
  <tuple>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">1874</atom>
        <atom name="NamFullName">Eliot Porter</atom>
        <atom name="SummaryData">Porter, Eliot</atom>
        <atom name="BioLabel">Eliot Porter (1901-1990)</atom>
        <atom name="NamSex">Male</atom>
        <atom name="BioNationality">American</atom>
        <atom name="BioEthnicity"></atom>
        <atom name="BioBirthDate">Dec.  6, 1901</atom>