<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 2000 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">62467</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1997.44</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Growth of Spring</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1919</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">9
5 15/16</atom>
    <atom name="MedValueMetric_tab">22.9
15.1</atom>
    <atom name="EdiEdition">Unknown</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.62467]</atom>
  </tuple>

  <!-- Row 2001 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">18132</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1997.43</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bacchantes</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1922</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Transfer lithograph and lithotint</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">6 15/16
5 1/4</atom>
    <atom name="MedValueMetric_tab">17.6
13.4</atom>
    <atom name="EdiEdition">?/25</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.18132]</atom>
  </tuple>

  <!-- Row 2002 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">136658</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1997.46</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">5357</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Stir of Shadowed Melody</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1920</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and lithotint on zinc</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 3/4
16
18 5/8
15 1/8</atom>
    <atom name="MedValueMetric_tab">27.31
40.64
47.31
38.42</atom>
    <atom name="EdiEdition">?/25</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.136658]</atom>
  </tuple>

  <!-- Row 2003 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">18095</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.39</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Donald Marron Collection</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">4788</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2892</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Toil of Three</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed by</atom>
    <atom name="CreType_tab">Date of Object
Date Printed</atom>
    <atom name="CreDateCreated_tab">1923-1924
ca. 1928-1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Aquatint</atom>
    <atom name="MedObjectType">Intaglio prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">6 11/16
3 7/16
11 7/8
8 7/16</atom>
    <atom name="MedValueMetric_tab">16.99
8.73
30.16
21.43</atom>
    <atom name="EdiEdition">35</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.18095]</atom>
  </tuple>

  <!-- Row 2004 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">89137</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1967.195</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas, In memory of John de Menil, Trustee, Amon Carter Museum of American Art, 1961-1969</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Blips and Ifs</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1963-1964</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on canvas</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">71 1/8
53 1/8</atom>
    <atom name="MedValueMetric_tab">180.66
134.94</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.89137]</atom>
  </tuple>

  <!-- Row 2005 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">94623</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1972.49</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">New Mexican Landscape</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1923</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on canvas</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">32
40 1/4</atom>
    <atom name="MedValueMetric_tab">81.3
102.3</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.94623]</atom>
  </tuple>

  <!-- Row 2006 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">115113</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1975.29</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Self-Portrait</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1919</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Oil on canvas</atom>
    <atom name="MedObjectType">Paintings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">22 1/4
18 1/4</atom>
    <atom name="MedValueMetric_tab">56.52
46.36</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.115113]</atom>
  </tuple>

  <!-- Row 2007 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">74573</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.45</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Adit</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">11 7/8
10 1/4
17 1/4
12 5/8</atom>
    <atom name="MedValueMetric_tab">30.16
26.04
43.82
32.07</atom>
    <atom name="EdiEdition">9/10</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.74573]</atom>
  </tuple>

  <!-- Row 2008 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">74574</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.46</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Drawing for "Adit"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">9 1/4
5 5/8</atom>
    <atom name="MedValueMetric_tab">23.5
14.3</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.74574]</atom>
  </tuple>

  <!-- Row 2009 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">5579</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.47</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Place des Vosges</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">9 3/4
13 7/8
12 3/4
19 3/4</atom>
    <atom name="MedValueMetric_tab">24.77
35.24
32.39
50.17</atom>
    <atom name="EdiEdition">6/10</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.5579]</atom>
  </tuple>

  <!-- Row 2010 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">16450</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.48</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Study for "Place des Vosges No.2"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">8 7/8
12 3/8</atom>
    <atom name="MedValueMetric_tab">22.54
31.43</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.16450]</atom>
  </tuple>

  <!-- Row 2011 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">7986</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.49</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Hotel de France</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">13 7/8
11
19
14 1/8</atom>
    <atom name="MedValueMetric_tab">35.24
27.94
48.26
35.88</atom>
    <atom name="EdiEdition">1/30</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.7986]</atom>
  </tuple>

  <!-- Row 2012 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">7985</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.50</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Study for Hotel de France</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">12 3/8
9 1/8</atom>
    <atom name="MedValueMetric_tab">31.43
23.18</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.7985]</atom>
  </tuple>

  <!-- Row 2013 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">141338</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.51</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Hotel Cafe</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928-1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 3/8
7 7/8
18 3/8
12 3/4</atom>
    <atom name="MedValueMetric_tab">26.35
20.
46.67
32.39</atom>
    <atom name="EdiEdition">3/30</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.141338]</atom>
  </tuple>

  <!-- Row 2014 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">118747</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.52</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Drawing for "Hotel Cafe"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">ca. 1928-1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">12 3/8
8 3/4</atom>
    <atom name="MedValueMetric_tab">31.43
22.23</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.118747]</atom>
  </tuple>

  <!-- Row 2015 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">124659</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.53</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Rue des Rats</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928-1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">10 1/8
15 1/4
13 7/8
18 7/8</atom>
    <atom name="MedValueMetric_tab">25.72
38.74
35.24
47.94</atom>
    <atom name="EdiEdition">2/30</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.124659]</atom>
  </tuple>

  <!-- Row 2016 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">55852</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.54</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Drawing for "Rue des Rats"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">10 5/8
15 5/8</atom>
    <atom name="MedValueMetric_tab">26.99
39.69</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.55852]</atom>
  </tuple>

  <!-- Row 2017 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">30626</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.55</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Au Bon Coin</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1929</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph and chine collé</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">7 7/8
10
12 3/4
19 3/4</atom>
    <atom name="MedValueMetric_tab">20
25.4
32.39
50.17</atom>
    <atom name="EdiEdition">1/30</atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.30626]</atom>
  </tuple>

  <!-- Row 2018 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">40424</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.56</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName">Stuart Davis Acquisition</atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3432</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Study for "Blue Café"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1928</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Graphite on paper</atom>
    <atom name="MedObjectType">Drawings</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">10 5/8
8 1/8</atom>
    <atom name="MedValueMetric_tab">26.99
20.64</atom>
    <atom name="EdiEdition"></atom>
    <atom name="RefCopyright_tab">© Estate of Stuart Davis/Licensed by VAGA, New York, NY</atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.40424]</atom>
  </tuple>

  <!-- Row 2019 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">73994</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1984.57</atom>
    <tuple name="AccAccessionLotRef">