<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    table           Group1
      integer         irn
    end
    text short      TitAccessionNo
    tuple           AccAccessionLotRef
      text long       AcqCreditLine
    end
    text long       WorAcmCollectionName
    table           CreCreatorRef_tab
      integer         irn
    end
    text long       TitMainTitle
    text long       TitParentTitle
    text long       CreRole_tab
    text long       CreType_tab
    text long       CreDateCreated_tab
    text short      MedFormat
    text long       MedMedium
    text short      MedObjectType
    text long       MedTechnique
    text long       MedType_tab
    text long       MedUnit_tab
    text long       MedUnitMetric_tab
    text long       MedValue_tab
    text long       MedValueMetric_tab
    text short      EdiEdition
    text long       RefCopyright_tab
    text long       ExhExhibitionRequirements
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 6000 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">63490</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.64</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Battle of Resaca de la Palma May 9th 1846. Capture of Genl. Vega by the gallant Capt. May.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1846</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8
12 3/4
10
14</atom>
    <atom name="MedValueMetric_tab">20.32
32.39
25.4
35.56</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.63490]</atom>
  </tuple>

  <!-- Row 6001 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">123123</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.63</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">General Z. Taylor, "Rough &amp; Ready." The Hero of Palo Alto, Reseca [sic] de la Palma, Monterey and Buena Vista.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">12 1/8
8 11/16
14 1/8
10 1/8</atom>
    <atom name="MedValueMetric_tab">30.8
22.07
35.88
25.72</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.123123]</atom>
  </tuple>

  <!-- Row 6002 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">46398</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.65</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Gallant Charge of the Kentucky Cavalry Under Col. Marshall, at the Battle of Buena Vista Febr. 23d. 1847.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 3/8
12 15/16
10
14</atom>
    <atom name="MedValueMetric_tab">21.27
32.86
25.4
35.56</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.46398]</atom>
  </tuple>

  <!-- Row 6003 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">13680</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.67</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Death of Major Ringgold. Of the Flying Artillery. At the Battle of Palo-Alto, (Texas) May 8th 1846.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1846</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 5/8
12 3/4
13 1/2
18 1/8</atom>
    <atom name="MedValueMetric_tab">21.91
32.39
34.29
46.04</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.13680]</atom>
  </tuple>

  <!-- Row 6004 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">127351</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.164</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Capitulation of Vera Cruz.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">7 3/4
12 1/2
9 7/8
13 7/8</atom>
    <atom name="MedValueMetric_tab">19.7
31.8
25
35.2</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.127351]</atom>
  </tuple>

  <!-- Row 6005 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">37280</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1972.43</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bombardment of Vera Cruz. March 25th 1847.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 3/8
12 7/8
10 1/4
14 1/8</atom>
    <atom name="MedValueMetric_tab">21.27
32.7
26.04
35.88</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.37280]</atom>
  </tuple>

  <!-- Row 6006 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">115977</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.57</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Grand, National, Whig Banner. Press Onward.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1848</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">11 13/16
9 1/4
13
9 3/8</atom>
    <atom name="MedValueMetric_tab">30.
23.5
33.02
23.81</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.115977]</atom>
  </tuple>

  <!-- Row 6007 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">96423</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.216</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Lady Suffolk.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1850</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">12 7/8
20 13/16
14 1/2
21 7/8</atom>
    <atom name="MedValueMetric_tab">32.7
52.86
36.83
55.56</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.96423]</atom>
  </tuple>

  <!-- Row 6008 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">44132</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.66</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Capture of Genl. La Vega by the Gallant Capt. May at the Battle of Resaca de la Palma May 9th 1846.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1846</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 1/2
12 3/4
10 3/8
14</atom>
    <atom name="MedValueMetric_tab">21.59
32.39
26.35
35.56</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.44132]</atom>
  </tuple>

  <!-- Row 6009 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">47341</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.65</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Genl. Taylor at the Battle of Resaca de la Palma.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1846</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 7/16
12 7/16
9 5/8
13 1/4</atom>
    <atom name="MedValueMetric_tab">21.43
31.59
24.45
33.66</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.47341]</atom>
  </tuple>

  <!-- Row 6010 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">121181</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1972.39</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">General Taylor and Staff. The Heroes of Palo Alto. Reseca [sic] de la Palma. Monterey and Buena Vista.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">12 3/16
8 9/16
14
9 7/8</atom>
    <atom name="MedValueMetric_tab">30.96
21.75
35.56
25.08</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.121181]</atom>
  </tuple>

  <!-- Row 6011 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">89658</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.163</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Brilliant Charge of Capt. May.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1846</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 5/8
12 3/4
10 9/16
14 3/8</atom>
    <atom name="MedValueMetric_tab">21.7
32.2
27
36.5</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.89658]</atom>
  </tuple>

  <!-- Row 6012 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">92281</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.62</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Battle of Cerro Gordo. Fought April 17th-18th 1847.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 3/4
12 5/8
10 1/8
14</atom>
    <atom name="MedValueMetric_tab">22.23
32.07
25.72
35.56</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.92281]</atom>
  </tuple>

  <!-- Row 6013 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">56222</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1983.165</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2114</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Landing of the American Forces Under Genl. Scott at Vera Cruz, March 9th, 1847</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1847</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">8 3/8
13 1/8
9 15/16
13 7/8</atom>
    <atom name="MedValueMetric_tab">21.1
33.2
25.4
35.3</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.56222]</atom>
  </tuple>

  <!-- Row 6014 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">59027</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.41</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">4875</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">San Francisco-California</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1874</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Steel engraving with applied watercolor</atom>
    <atom name="MedObjectType">Intaglio prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Height
Width</atom>
    <atom name="MedUnit_tab">inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm</atom>
    <atom name="MedValue_tab">8 3/4
24 3/8</atom>
    <atom name="MedValueMetric_tab">22.23
61.91</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.59027]</atom>
  </tuple>

  <!-- Row 6015 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">19186</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.58</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">1514</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">Bird's Eye View of Quinnesec, Mich. 1881.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1881</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Toned lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">6 7/8
12
10
14 1/4</atom>
    <atom name="MedValueMetric_tab">17.46
30.48
25.4
36.2</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.19186]</atom>
  </tuple>

  <!-- Row 6016 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">68223</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1971.56</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2035</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">The Republican Banner for 1860.</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1860</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Lithograph with applied watercolor</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">12
8 5/8
13 1/4
9 13/16</atom>
    <atom name="MedValueMetric_tab">30.48
21.91
33.66
24.92</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.68223]</atom>
  </tuple>

  <!-- Row 6017 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">117696</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.198</atom>
    <tuple name="AccAccessionLotRef">
      <atom name="AcqCreditLine">Amon Carter Museum of American Art, Fort Worth, Texas</atom>
    </tuple>
    <atom name="WorAcmCollectionName"></atom>
    <table name="CreCreatorRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2206</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2035</atom>
      </tuple>
    </table>
    <atom name="TitMainTitle">"Thistle"</atom>
    <atom name="TitParentTitle"></atom>
    <atom name="CreRole_tab">Artist
Printed and published by</atom>
    <atom name="CreType_tab">Date of Object</atom>
    <atom name="CreDateCreated_tab">1887</atom>
    <atom name="MedFormat"></atom>
    <atom name="MedMedium">Chromolithograph</atom>
    <atom name="MedObjectType">Planographic prints</atom>
    <atom name="MedTechnique"></atom>
    <atom name="MedType_tab">Image Height
Image Width
Sheet Height
Sheet Width</atom>
    <atom name="MedUnit_tab">inches
inches
inches
inches</atom>
    <atom name="MedUnitMetric_tab">cm
cm
cm
cm</atom>
    <atom name="MedValue_tab">20
27 7/8
24 3/4
31 9/16</atom>
    <atom name="MedValueMetric_tab">50.8
70.8
62.87
80.17</atom>
    <atom name="EdiEdition"></atom>
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.117696]</atom>
  </tuple>

  <!-- Row 6018 -->
  <tuple>
    <table name="Group1">
      <tuple>
        <atom name="InternalRecordNumber">22738</atom>
      </tuple>
    </table>
    <atom name="TitAccessionNo">1970.59</atom>
    <tuple name="AccAccessionLotRef">