<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           eevents
    text long       EveEventTitle
    date            DatCommencementDate
    date            DatCompletionDate
    table           EveEventOrganisersRef_tab
      text short      NamFullName
    end
    table           VenVenueNameRef_tab
      text short      NamFullName
    end
    table           ObjAttachedObjectsRef_tab
      integer         irn
    end
    table           EveBibliograpyRef_tab
      integer         irn
    end
  end
?>
<!-- Data -->
<table name="eevents">

  <!-- Row 1 -->
  <tuple>
    <atom name="EveEventTitle">Third Annual Exhibition</atom>
    <atom name="DatCommencementDate">1828-05-05</atom>
    <atom name="DatCompletionDate">1828-07-10</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">12450</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="EveEventTitle">Paintings by Thomas Cole</atom>
    <atom name="DatCommencementDate">1828-08-</atom>
    <atom name="DatCompletionDate">1828-08-</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Boston Athenaeum</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Boston Athenaeum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">12450</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="EveEventTitle">The Sixth Annual Exhibition</atom>
    <atom name="DatCommencementDate">1831-05-</atom>
    <atom name="DatCompletionDate">1831-06-25</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">12450</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="EveEventTitle">Exhibition of the Paintings of the Late Thomas Cole</atom>
    <atom name="DatCommencementDate">1848</atom>
    <atom name="DatCompletionDate">1848</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">American Art-Union</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">American Art-Union</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">142656</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3038</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="EveEventTitle">Summer Exhibition</atom>
    <atom name="DatCommencementDate">1862</atom>
    <atom name="DatCompletionDate">1862</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Royal Academy of Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Royal Academy of Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">192602</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="EveEventTitle">Art Exhibition at the Metropolitan Fair, in the Aid of the U.S. Sanitary Commission</atom>
    <atom name="DatCommencementDate">1864</atom>
    <atom name="DatCompletionDate">1864</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Metropolitan Fair</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Metropolitan Fair</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">15013</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="EveEventTitle">42nd Annual Exhibition of the National Academy of Design</atom>
    <atom name="DatCommencementDate">1867</atom>
    <atom name="DatCompletionDate">1867</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">151423</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="EveEventTitle">First Annual Exhibition of the Yale School of the Fine Arts</atom>
    <atom name="DatCommencementDate">1867</atom>
    <atom name="DatCompletionDate">1867</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Yale University</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Yale University</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">151423</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2992</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 9 -->
  <tuple>
    <atom name="EveEventTitle">Spring Exhibition</atom>
    <atom name="DatCommencementDate">1868-03-18</atom>
    <atom name="DatCompletionDate">1868-03-21</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Brooklyn Art Association</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Brooklyn Art Association</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">68100</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 10 -->
  <tuple>
    <atom name="EveEventTitle">Forty-Third Annual Exhibition</atom>
    <atom name="DatCommencementDate">1868-04-15</atom>
    <atom name="DatCompletionDate">1868-06-20</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">68100</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 11 -->
  <tuple>
    <atom name="EveEventTitle">Second Annual Collection of the American Society of Painters in Water Colors</atom>
    <atom name="DatCommencementDate">1869-01-22</atom>
    <atom name="DatCompletionDate">1869-01-22</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">American Society of Painters in Water Colors</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Columbia University</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">139193</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 12 -->
  <tuple>
    <atom name="EveEventTitle">Catalogue Descriptive and Instructive of Catlin's Indian Cartoons</atom>
    <atom name="DatCommencementDate">1871-10-</atom>
    <atom name="DatCompletionDate">1871-10-</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Somerville Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Somerville Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">93976</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2835</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 13 -->
  <tuple>
    <atom name="EveEventTitle">Annual Exhibition</atom>
    <atom name="DatCommencementDate">1872-01-13</atom>
    <atom name="DatCompletionDate">1872-01-13</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Century Association</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Century Association</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">97468</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 14 -->
  <tuple>
    <atom name="EveEventTitle">Forty-Seventh Annual Exhibition of the National Academy of Design</atom>
    <atom name="DatCommencementDate">1872-04-12</atom>
    <atom name="DatCompletionDate">1872-07-06</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">97468</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 15 -->
  <tuple>
    <atom name="EveEventTitle">Forty-Ninth Annual Exhibition of the National Academy of Design</atom>
    <atom name="DatCommencementDate">1874</atom>
    <atom name="DatCompletionDate">1874</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">130049</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2387</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 16 -->
  <tuple>
    <atom name="EveEventTitle">Interstate Industrial Exposition</atom>
    <atom name="DatCommencementDate">1875</atom>
    <atom name="DatCompletionDate">1875</atom>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Interstate Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">97468</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 17 -->
  <tuple>
    <atom name="EveEventTitle">Ninth Annual Exhibition of the American Society of Painters in Water Colors</atom>
    <atom name="DatCommencementDate">1876-01-31</atom>
    <atom name="DatCompletionDate">1876-02-26</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">33815</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2865</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 18 -->
  <tuple>
    <atom name="EveEventTitle">Centennial Exposition</atom>
    <atom name="DatCommencementDate">1876</atom>
    <atom name="DatCompletionDate">1876</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Centennial Exposition</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Centennial Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">93976</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">130049</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 19 -->
  <tuple>
    <atom name="EveEventTitle">Fifty-Second Annual Exhibition</atom>
    <atom name="DatCommencementDate">1877</atom>
    <atom name="DatCompletionDate">1877</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">69163</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2866</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 20 -->
  <tuple>
    <atom name="EveEventTitle">Fifty-Seventh Annual Exhibition of the National Academy of Design</atom>
    <atom name="DatCommencementDate">1882-03-27</atom>
    <atom name="DatCompletionDate">1882-05-</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">128402</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2899</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 21 -->
  <tuple>
    <atom name="EveEventTitle">National Academy of Design Figure Competition Prize Fund Exhibition of Clarke Pictures</atom>
    <atom name="DatCommencementDate">1883-12-28</atom>
    <atom name="DatCompletionDate">1884-01-12</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">128402</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2795</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 22 -->
  <tuple>
    <atom name="EveEventTitle">New England Manufacturers' and Mechanics' Institute Exposition</atom>
    <atom name="DatCommencementDate">1883</atom>
    <atom name="DatCompletionDate">1883</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">New England Manufacturers' and Mechanics' Institute</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">New England Manufacturers' and Mechanics' Institute</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">128402</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2901</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 23 -->
  <tuple>
    <atom name="EveEventTitle">Pennsylvania Academy of Fine Arts 56th Annual Exhibition</atom>
    <atom name="DatCommencementDate">1885-10-29</atom>
    <atom name="DatCompletionDate">1885-12-10</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">29677</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2816</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 24 -->
  <tuple>
    <atom name="EveEventTitle">Gallery of the Southern Exposition</atom>
    <atom name="DatCommencementDate">1886-08-28</atom>
    <atom name="DatCompletionDate">1886-10-23</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Louisville Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Louisville Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 25 -->
  <tuple>
    <atom name="EveEventTitle">15th Annual Exhibition</atom>
    <atom name="DatCommencementDate">1887-09-07</atom>
    <atom name="DatCompletionDate">1887-10-22</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Interstate Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Interstate Industrial Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">29677</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 26 -->
  <tuple>
    <atom name="EveEventTitle">Centennial Exposition of the Ohio Valley and Central States</atom>
    <atom name="DatCommencementDate">1888</atom>
    <atom name="DatCompletionDate">1888</atom>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">8041</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 27 -->
  <tuple>
    <atom name="EveEventTitle">Fifty-Ninth Annual Exhibition</atom>
    <atom name="DatCommencementDate">1889-01-24</atom>
    <atom name="DatCompletionDate">1889-03-07</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">50684</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2767</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 28 -->
  <tuple>
    <atom name="EveEventTitle">Annual Exhibition</atom>
    <atom name="DatCommencementDate">1889-04-01</atom>
    <atom name="DatCompletionDate">1889-05-11</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">177588</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 29 -->
  <tuple>
    <atom name="EveEventTitle">Eighth Autumn Exhibition</atom>
    <atom name="DatCommencementDate">1889</atom>
    <atom name="DatCompletionDate">1889</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">National Academy of Design</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">48884</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 30 -->
  <tuple>
    <atom name="EveEventTitle">Paintings Exhibited by American Artists</atom>
    <atom name="DatCommencementDate">1890-04-07</atom>
    <atom name="DatCompletionDate">1890</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Association</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Association</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">58269</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2984</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 31 -->
  <tuple>
    <atom name="EveEventTitle">Twelfth Exhibition of the Society of American Artists</atom>
    <atom name="DatCommencementDate">1890-04-08</atom>
    <atom name="DatCompletionDate">1890-05-24</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Society of American Artists</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Society of American Artists</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">63538</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3117</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 32 -->
  <tuple>
    <atom name="EveEventTitle">Paintings by American Artists</atom>
    <atom name="DatCommencementDate">1890</atom>
    <atom name="DatCompletionDate">1890</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Gallery</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">American Art Gallery</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">48884</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 33 -->
  <tuple>
    <atom name="EveEventTitle">Thomas B. Clarke Collection of American Pictures</atom>
    <atom name="DatCommencementDate">1891-10-15</atom>
    <atom name="DatCompletionDate">1891-11-28</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Pennsylvania Academy of the Fine Arts</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">128402</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2798</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 34 -->
  <tuple>
    <atom name="EveEventTitle">Catalogue of the Art Collection of the St. Louis Exposition and Music Hall Association, Ninth Annual Exhibition</atom>
    <atom name="DatCommencementDate">1892</atom>
    <atom name="DatCompletionDate">1892</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">St. Louis Exposition</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">St. Louis Exposition</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">54553</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 35 -->
  <tuple>
    <atom name="EveEventTitle">St. Louis Exposition, 10th Annual Exhibition</atom>
    <atom name="DatCommencementDate">1893-10-</atom>
    <atom name="DatCompletionDate">1893-10-</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Saint Louis Art Museum</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Saint Louis Art Museum</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">48884</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 36 -->
  <tuple>
    <atom name="EveEventTitle">World's Columbian Exposition</atom>
    <atom name="DatCommencementDate">1893</atom>
    <atom name="DatCompletionDate">1893</atom>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">16804</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2353</atom>
      </tuple>
      <tuple>
        <atom name="InternalRecordNumber">2361</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 37 -->
  <tuple>
    <atom name="EveEventTitle">First Annual Exhibition of the Cleveland Art Association</atom>
    <atom name="DatCommencementDate">1895-01-22</atom>
    <atom name="DatCompletionDate">1895-02-22</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Cleveland Art Association</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Cleveland Art Association</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">98114</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">3819</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 38 -->
  <tuple>
    <atom name="EveEventTitle">The Cotton State and International Exposition, 1895</atom>
    <atom name="DatCommencementDate">1895-09-18</atom>
    <atom name="DatCompletionDate">1895-12-31</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">High Museum of Art</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Piedmont Park</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">16804</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 39 -->
  <tuple>
    <atom name="EveEventTitle">Seventeenth Annual Exhibition</atom>
    <atom name="DatCommencementDate">1895</atom>
    <atom name="DatCompletionDate">1895</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>
        <atom name="NamFullName">Society of American Artists</atom>
      </tuple>
    </table>
    <table name="VenVenueNameRef_tab">
      <tuple>
        <atom name="NamFullName">Society of American Artists</atom>
      </tuple>
    </table>
    <table name="ObjAttachedObjectsRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">98114</atom>
      </tuple>
    </table>
    <table name="EveBibliograpyRef_tab">
      <tuple>
        <atom name="InternalRecordNumber">2308</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 40 -->
  <tuple>
    <atom name="EveEventTitle">Tennessee Centennial</atom>
    <atom name="DatCommencementDate">1897</atom>
    <atom name="DatCompletionDate">1897</atom>
    <table name="EveEventOrganisersRef_tab">
      <tuple>